services:
  voting-voter:
    build:
      context: .
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=tata
      - DB_NAME=testdb
    networks:
      - database_net
networks:
  database_net:
    external: true
    name: my_shared_network
