server.port=8083
database.url=jdbc:postgresql://localhost
database.name=testdb
database.username=postgres
database.password=tata
spring.application.name=voting-service
eureka.client.serviceUrl.defaultZone=http://localhost:8084/eureka/
