server.port=8081
database.url=jdbc:postgresql://creator_db
database.name=testdb
database.username=postgres
database.password=tata
spring.application.name=voting-creator
eureka.client.serviceUrl.defaultZone=http://192.168.0.161:8084/eureka/
